" Name:         phlebotinum
" Version:      1.1.0
" Description:  When the Apprentice got his hands on some magic Beans.
" Author:       Curly-Mo <github.com/Curly-Mo>
" Maintainer:   Colin <colin@cfahy.com>
" URL:          https://github.com/Curly-Mo
" License:      LGPL
" Last Updated: Mon 01 Nov 2021 08:49:39 PM EDT

" Generated by Colortemplate v2.1.0

set background=dark

hi clear
let g:colors_name = 'phlebotinum'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 1
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#181818', '#cf6a4c', '#5f875f', '#af5f00', '#5f87af', '#5f5f87', '#5f8787', '#6c6c6c', '#262626', '#fac863', '#99ad6a', '#e6db74', '#5f87af', '#8787af', '#00a7aa', '#bcbcbc']
  if has('nvim')
    let g:terminal_color_0 = '#181818'
    let g:terminal_color_1 = '#cf6a4c'
    let g:terminal_color_2 = '#5f875f'
    let g:terminal_color_3 = '#af5f00'
    let g:terminal_color_4 = '#5f87af'
    let g:terminal_color_5 = '#5f5f87'
    let g:terminal_color_6 = '#5f8787'
    let g:terminal_color_7 = '#6c6c6c'
    let g:terminal_color_8 = '#262626'
    let g:terminal_color_9 = '#fac863'
    let g:terminal_color_10 = '#99ad6a'
    let g:terminal_color_11 = '#e6db74'
    let g:terminal_color_12 = '#5f87af'
    let g:terminal_color_13 = '#8787af'
    let g:terminal_color_14 = '#00a7aa'
    let g:terminal_color_15 = '#bcbcbc'
  endif
  let s:bg_color = get(g:, 'phlebotinum_bg', 'NONE')
  if s:bg_color != "NONE" && s:bg_color != "none"
    hi Normal guifg=#bcbcbc guibg=#262626 gui=NONE cterm=NONE
  else
    hi Normal guifg=#bcbcbc guibg=NONE gui=NONE cterm=NONE
  endif
  hi NonText guifg=#6c6c6c guibg=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#6c6c6c guibg=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#6c6c6c guibg=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#6c6c6c guibg=NONE gui=NONE cterm=NONE
  hi Folded guifg=#6c6c6c guibg=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#fac863 guibg=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#6c6c6c guibg=NONE gui=NONE cterm=NONE
  hi Comment guifg=#8090a0 guibg=NONE gui=italic cterm=italic
  hi Conceal guifg=#bcbcbc guibg=NONE gui=NONE cterm=NONE
  hi Constant guifg=#cf6a4c guibg=NONE gui=NONE cterm=NONE
  hi Number guifg=#af5f5f guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#cf6a4c guibg=NONE gui=reverse cterm=reverse
  hi Identifier guifg=#5f8787 guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PreProc guifg=#5f87af guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#5f5f87 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#af5f00 guibg=NONE gui=NONE cterm=NONE
  hi String guifg=#af5f5f guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi Type guifg=#5f875f guibg=NONE gui=NONE cterm=NONE
  hi TypeDef guifg=#5f5f87 guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#5f8787 guibg=NONE gui=underline cterm=underline
  hi Pmenu guifg=#bcbcbc guibg=#303030 gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#303030 gui=NONE cterm=NONE
  hi PmenuSel guifg=#5f5f87 guibg=NONE gui=reverse cterm=reverse
  hi PmenuThumb guifg=#121212 guibg=#121212 gui=NONE cterm=NONE
  hi ErrorMsg guifg=#cf6a4c guibg=NONE gui=reverse cterm=reverse
  hi ModeMsg guifg=#99ad6a guibg=NONE gui=reverse cterm=reverse
  hi MoreMsg guifg=#5f8787 guibg=NONE gui=NONE cterm=NONE
  hi Question guifg=#99ad6a guibg=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#cf6a4c guibg=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#87875f guibg=#444444 gui=NONE cterm=NONE
  hi TabLineFill guifg=#444444 guibg=#444444 gui=NONE cterm=NONE
  hi TabLineSel guifg=#87875f guibg=NONE gui=reverse cterm=reverse
  hi ToolbarLine guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ToolbarButton guifg=#bcbcbc guibg=#6c6c6c gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=#6c6c6c gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#303030 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#bcbcbc guibg=#1c1c1c gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#1c1c1c gui=NONE cterm=NONE
  hi helpLeadBlank guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi helpNormal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi StatusLine guifg=#6c6c6c guibg=#121212 gui=NONE cterm=NONE
  hi StatusLineNC guifg=#bcbcbc guibg=#121212 gui=NONE cterm=NONE
  hi Visual guifg=#8fafd7 guibg=NONE gui=reverse cterm=reverse
  hi VisualNOS guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi VertSplit guifg=#6c6c6c guibg=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#8fafd7 guibg=NONE gui=reverse cterm=reverse
  hi Function guifg=#5f87af guibg=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#6c6c6c guibg=NONE gui=NONE cterm=NONE
  hi Title guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#5f875f guibg=NONE gui=reverse cterm=reverse
  hi DiffChange guifg=#8787af guibg=NONE gui=reverse cterm=reverse
  hi DiffDelete guifg=#703020 guibg=NONE gui=reverse cterm=reverse
  hi DiffText guifg=#af5f00 guibg=NONE gui=reverse cterm=reverse
  hi IncSearch guifg=#262626 guibg=NONE gui=underline cterm=underline
  hi Search guifg=#c594c5 guibg=NONE gui=underline cterm=underline
  hi Directory guifg=#00a7aa guibg=NONE gui=NONE cterm=NONE
  hi debugPC guifg=NONE guibg=#5f87af gui=NONE cterm=NONE
  hi debugBreakpoint guifg=NONE guibg=#cf6a4c gui=NONE cterm=NONE
  hi SpellBad guifg=#cf6a4c guibg=NONE gui=undercurl cterm=undercurl
  hi SpellCap guifg=#00a7aa guibg=NONE gui=undercurl cterm=undercurl
  hi SpellLocal guifg=#5f875f guibg=NONE gui=undercurl cterm=undercurl
  hi SpellRare guifg=#fac863 guibg=NONE gui=undercurl cterm=undercurl
  hi ColorColumn guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi GitGutterAdd guifg=#5f875f guibg=NONE gui=NONE cterm=NONE
  hi GitGutterChange guifg=#8787af guibg=NONE gui=NONE cterm=NONE
  hi GitGutterDelete guifg=#703020 guibg=NONE gui=NONE cterm=NONE
  hi! link Terminal Normal
  hi! link CursorIM Cursor
  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Conditional Statement
  hi! link Debug Special
  hi! link Define PreProc
  hi! link Delimiter Special
  hi! link Exception Statement
  hi! link Float Number
  hi! link HelpCommand Statement
  hi! link HelpExample Statement
  hi! link Include PreProc
  hi! link Keyword Statement
  hi! link Label Statement
  hi! link Macro PreProc
  hi! link Operator Statement
  hi! link PreCondit PreProc
  hi! link Repeat Statement
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi! link StorageClass Type
  hi! link Structure Type
  hi! link Tag Special
  hi! link Terminal Normal
  hi! link Typedef Type
  hi! link htmlEndTag htmlTagName
  hi! link htmlLink Function
  hi! link htmlSpecialTagName htmlTagName
  hi! link htmlTag htmlTagName
  hi! link htmlBold Normal
  hi! link htmlItalic Normal
  hi! link xmlTag Statement
  hi! link xmlTagName Statement
  hi! link xmlEndTag Statement
  hi! link markdownItalic Preproc
  hi! link asciidocQuotedEmphasized Preproc
  hi! link diffBDiffer WarningMsg
  hi! link diffCommon WarningMsg
  hi! link diffDiffer WarningMsg
  hi! link diffIdentical WarningMsg
  hi! link diffIsA WarningMsg
  hi! link diffNoEOL WarningMsg
  hi! link diffOnly WarningMsg
  hi! link diffRemoved WarningMsg
  hi! link diffAdded String
  hi! link QuickFixLine Search
  hi! link TSConstBuiltin Constant
  hi! link TSStringRegex SpecialChar
  hi! link TSStringEscape Character
  hi! link TSFuncBuiltin Function
  hi! link TSConstructor Typedef
  hi! link TSVariableBuiltin Identifier
  hi! link TSURI Tag
  hi TSConstBuiltin guifg=#875f87 guibg=NONE gui=NONE cterm=NONE
  hi TSFuncBuiltin guifg=#5f8787 guibg=NONE gui=NONE cterm=NONE
  hi TSParameter guifg=#8787af guibg=NONE gui=NONE cterm=NONE
  hi TSParameterReference guifg=#8787af guibg=NONE gui=NONE cterm=NONE
  hi TSOperator guifg=#af5f00 guibg=NONE gui=NONE cterm=NONE
  hi TSTypeBuiltin guifg=#875f87 guibg=NONE gui=NONE cterm=NONE
  hi TSVariableBuiltin guifg=#875f87 guibg=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  let s:bg_color = get(g:, 'phlebotinum_bg', 'NONE')
  if s:bg_color != "NONE" && s:bg_color != "none"
    hi Normal ctermfg=250 ctermbg=235 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
  else
    hi Normal ctermfg=250 ctermbg=NONE cterm=NONE
  endif
  hi NonText ctermfg=242 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=242 ctermbg=NONE cterm=NONE
  hi LineNr ctermfg=242 ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=242 ctermbg=NONE cterm=NONE
  hi Folded ctermfg=242 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=222 ctermbg=NONE cterm=NONE
  hi SignColumn ctermfg=242 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=245 ctermbg=NONE cterm=italic
  hi Conceal ctermfg=250 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=173 ctermbg=NONE cterm=NONE
  hi Number ctermfg=131 ctermbg=NONE cterm=NONE
  hi Error ctermfg=173 ctermbg=NONE cterm=reverse
  hi Identifier ctermfg=66 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=67 ctermbg=NONE cterm=NONE
  hi Special ctermfg=60 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=130 ctermbg=NONE cterm=NONE
  hi String ctermfg=131 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=NONE ctermbg=NONE cterm=reverse
  hi Type ctermfg=65 ctermbg=NONE cterm=NONE
  hi TypeDef ctermfg=60 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=66 ctermbg=NONE cterm=underline
  hi Pmenu ctermfg=250 ctermbg=236 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=236 cterm=NONE
  hi PmenuSel ctermfg=60 ctermbg=NONE cterm=reverse
  hi PmenuThumb ctermfg=233 ctermbg=233 cterm=NONE
  hi ErrorMsg ctermfg=173 ctermbg=NONE cterm=reverse
  hi ModeMsg ctermfg=107 ctermbg=NONE cterm=reverse
  hi MoreMsg ctermfg=66 ctermbg=NONE cterm=NONE
  hi Question ctermfg=107 ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=173 ctermbg=NONE cterm=NONE
  hi TabLine ctermfg=101 ctermbg=238 cterm=NONE
  hi TabLineFill ctermfg=238 ctermbg=238 cterm=NONE
  hi TabLineSel ctermfg=101 ctermbg=NONE cterm=reverse
  hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ToolbarButton ctermfg=250 ctermbg=242 cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=242 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=236 cterm=NONE
  hi CursorLineNr ctermfg=250 ctermbg=234 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=234 cterm=NONE
  hi helpLeadBlank ctermfg=NONE ctermbg=NONE cterm=NONE
  hi helpNormal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=242 ctermbg=233 cterm=NONE
  hi StatusLineNC ctermfg=250 ctermbg=233 cterm=NONE
  hi Visual ctermfg=110 ctermbg=NONE cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=underline
  hi VertSplit ctermfg=242 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=110 ctermbg=NONE cterm=reverse
  hi Function ctermfg=67 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=242 ctermbg=NONE cterm=NONE
  hi Title ctermfg=231 ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=65 ctermbg=NONE cterm=reverse
  hi DiffChange ctermfg=103 ctermbg=NONE cterm=reverse
  hi DiffDelete ctermfg=88 ctermbg=NONE cterm=reverse
  hi DiffText ctermfg=130 ctermbg=NONE cterm=reverse
  hi IncSearch ctermfg=235 ctermbg=NONE cterm=underline
  hi Search ctermfg=139 ctermbg=NONE cterm=underline
  hi Directory ctermfg=37 ctermbg=NONE cterm=NONE
  hi debugPC ctermfg=NONE ctermbg=67 cterm=NONE
  hi debugBreakpoint ctermfg=NONE ctermbg=173 cterm=NONE
  hi SpellBad ctermfg=173 ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=37 ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=65 ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=222 ctermbg=NONE cterm=undercurl
  hi ColorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi GitGutterAdd ctermfg=65 ctermbg=NONE cterm=NONE
  hi GitGutterChange ctermfg=103 ctermbg=NONE cterm=NONE
  hi GitGutterDelete ctermfg=88 ctermbg=NONE cterm=NONE
  hi! link Terminal Normal
  hi! link CursorIM Cursor
  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Conditional Statement
  hi! link Debug Special
  hi! link Define PreProc
  hi! link Delimiter Special
  hi! link Exception Statement
  hi! link Float Number
  hi! link HelpCommand Statement
  hi! link HelpExample Statement
  hi! link Include PreProc
  hi! link Keyword Statement
  hi! link Label Statement
  hi! link Macro PreProc
  hi! link Operator Statement
  hi! link PreCondit PreProc
  hi! link Repeat Statement
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi! link StorageClass Type
  hi! link Structure Type
  hi! link Tag Special
  hi! link Terminal Normal
  hi! link Typedef Type
  hi! link htmlEndTag htmlTagName
  hi! link htmlLink Function
  hi! link htmlSpecialTagName htmlTagName
  hi! link htmlTag htmlTagName
  hi! link htmlBold Normal
  hi! link htmlItalic Normal
  hi! link xmlTag Statement
  hi! link xmlTagName Statement
  hi! link xmlEndTag Statement
  hi! link markdownItalic Preproc
  hi! link asciidocQuotedEmphasized Preproc
  hi! link diffBDiffer WarningMsg
  hi! link diffCommon WarningMsg
  hi! link diffDiffer WarningMsg
  hi! link diffIdentical WarningMsg
  hi! link diffIsA WarningMsg
  hi! link diffNoEOL WarningMsg
  hi! link diffOnly WarningMsg
  hi! link diffRemoved WarningMsg
  hi! link diffAdded String
  hi! link QuickFixLine Search
  hi! link TSConstBuiltin Constant
  hi! link TSStringRegex SpecialChar
  hi! link TSStringEscape Character
  hi! link TSFuncBuiltin Function
  hi! link TSConstructor Typedef
  hi! link TSVariableBuiltin Identifier
  hi! link TSURI Tag
  hi TSConstBuiltin ctermfg=96 ctermbg=NONE cterm=NONE
  hi TSFuncBuiltin ctermfg=66 ctermbg=NONE cterm=NONE
  hi TSParameter ctermfg=103 ctermbg=NONE cterm=NONE
  hi TSParameterReference ctermfg=103 ctermbg=NONE cterm=NONE
  hi TSOperator ctermfg=130 ctermbg=NONE cterm=NONE
  hi TSTypeBuiltin ctermfg=96 ctermbg=NONE cterm=NONE
  hi TSVariableBuiltin ctermfg=96 ctermbg=NONE cterm=NONE
  if !s:italics
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: trueblack     rgb(  0,  0,  0)          ~         Black
" Color: darkerblack   #080808                   ~         Black
" Color: darkblack     #121212                   ~         Black
" Color: black         #181818                   ~         Black
" Color: black2        #1c1c1c                   ~         Black
" Color: lightblack    #262626                   ~         Black
" Color: lightblack2   #303030                   ~         LightGrey
" Color: lightblack3   #444444                   ~         LightGrey
" Color: darkgrey      #585858                   ~         LightGrey
" Color: grey          #6c6c6c                   ~         LightGrey
" Color: lightgrey     #808080                   ~         LightGrey
" Color: lightgrey2    #c0c5ce                   ~         LightGrey
" Color: lightgrey3    #cdd3de                   ~         LightGrey
" Color: coolgrey      #4f5b66                   ~         DarkGrey
" Color: coolgrey2     #65737e                   ~         DarkGrey
" Color: coolgrey3     #8090a0                   ~         DarkGrey
" Color: coolgrey4     #a7adba                   ~         DarkGrey
" Color: darkwhite     #888888                   ~         DarkGrey
" Color: darkwhite2    #d8dee9                   ~         White
" Color: white         #bcbcbc                   ~         White
" Color: darkred       #5f0000                   ~         DarkRed
" Color: darkred2      #703020                   ~         DarkRed
" Color: red           #af5f5f                   ~         Red
" Color: lightred      #cf6a4c                   ~         Red
" Color: lightred2     #ab7967                   ~         Red
" Color: brown         #af5f00                   ~         Brown
" Color: orange        #fac863                   ~         Brown
" Color: orange2       #ffba7b                   ~         Brown
" Color: orange3       #ffb964                   ~         Brown
" Color: orange4       #f39b35                   ~         Brown
" Color: yellow        #e6db74                   ~         LightYellow
" Color: wheat         #87875f                   ~         Brown
" Color: green         #5f875f                   ~         DarkGreen
" Color: green2        #99ad6a                   ~         Green
" Color: green3        #87af87                   ~         Green
" Color: teal          #5f8787                   ~         DarkCyan
" Color: cyan          #008080                   ~         DarkCyan
" Color: cyan2         #00a7aa                   ~         LightCyan
" Color: cyan3         #5fafaf                   ~         LightCyan
" Color: cyan4         #5fb3b3                   ~         LightCyan
" Color: lightblue     #b1d8f6                   ~         Blue
" Color: lightblue2    #8fbfdc                   ~         Blue
" Color: lightblue3    #8fafd7                   ~         Blue
" Color: lightblue4    #8197bf                   ~         Blue
" Color: blue          #5f87af                   ~         DarkBlue
" Color: blue2         #7587a6                   ~         DarkBlue
" Color: purple        #5f5f87                   ~         DarkMagenta
" Color: purple2       #8787af                   ~         DarkMagenta
" Color: purple3       #875f87                   ~         DarkMagenta
" Color: pink          #c6b6ee                   ~         Magenta
" Color: pink2         #c594c5                   ~         Magenta
" Color: pink3         #d7afff                   ~         Magenta
" Color: br_green      #008080                   ~         LightGreen
" Color: br_yellow     #ffffaf                   ~         Yellow
" Color: br_orange     #ff8700                   ~         LightYellow
" Color: br_blue       #8fafd7                   ~         LightBlue
" Color: br_purple     #c594c5                   ~         LightMagenta
" Color: br_cyan       #5fb3b3                   ~         LightCyan
" Color: br_white      #ffffff                   ~         White
" Color: fg_           #bcbcbc                   ~         Grey
"   Color: bg_           #262626              ~         Black
" Term colors: black lightred green brown blue purple teal grey
" Term colors: lightblack orange green2 yellow
" Term colors: blue purple2 cyan2 white
" vim: et ts=2 sw=2
